In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv("customer_churn.csv")
data.head()

   Customer_ID  Days_since_last_order  Orders_last_6_months  App_Login  Churn
0          101                     60                     1          2      1
1          102                      5                    20         25      0
2          103                     45                     3          5      1
3          104                      8                    18         22      0
4          105                     55                     2          4      1

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            20 non-null     int64
 1   Days_since_last_order  20 non-null     int64
 2   Orders_last_6_months   20 non-null     int64
 3   App_Login              20 non-null     int64
 4   Churn                  20 non-null     int64
dtypes: int64(5)
memory usage: 932.0 bytes

In [ ]:
data.isnull().sum()

Customer_ID              0
Days_since_last_order    0
Orders_last_6_months     0
App_Login                0
Churn                    0
dtype: int64

In [ ]:
data.fillna(0,inplace=True)

In [ ]:
data["Churn"].value_counts()

Churn
1    10
0    10
Name: count, dtype: int64

In [ ]:
data.describe()

,Customer_ID,Days_since_last_order,Orders_last_6_months,App_Login,Churn
count,20.00000,20.000000,20.000000,20.000000,20.000000
mean,110.50000,27.000000,12.000000,16.000000,0.500000
std,5.91608,20.845295,9.973649,11.069161,0.512989
min,101.00000,3.000000,1.000000,2.000000,0.000000
25%,105.75000,7.750000,2.750000,5.750000,0.000000
50%,110.50000,23.500000,10.500000,15.500000,0.500000
75%,115.25000,45.750000,19.250000,24.250000,1.000000
max,120.00000,60.000000,30.000000,35.000000,1.000000

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
X=data[[
"Days_since_last_order",
"Orders_last_6_months",
"App_Login"
]]

y=data["Churn"]

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(
X,y,test_size=0.2
)

In [ ]:
model=LogisticRegression()

model.fit(X_train,y_train)

LogisticRegression()

In [ ]:
pred=model.predict(X_test)

In [ ]:
accuracy_score(y_test,pred)

1.0

In [ ]:
prediction=model.predict(X_test)

print(prediction)

[1 0 0 1]

In [ ]:
print("Actual:",list(y_test))
print("Predicted:",list(prediction))

Actual: [1, 0, 0, 1]
Predicted: [np.int64(1), np.int64(0), np.int64(0), np.int64(1)]

In [ ]:
prediction=model.predict(X_test)

print("Predicted:", prediction.tolist())

Predicted: [1, 0, 0, 1]

In [ ]:
print("Actual:", y_test.tolist())
print("Predicted:", prediction.tolist())

Actual: [1, 0, 0, 1]
Predicted: [1, 0, 0, 1]

In [ ]:
prediction=model.predict(X_test)

print("Predicted:", prediction.tolist())

Predicted: [1, 0, 0, 1]

In [ ]:
result = X_test.copy()

result["Actual"] = y_test.values

result["Predicted"] = prediction

result

    Days_since_last_order  Orders_last_6_months  App_Login  Actual  Predicted
18                     38                     5         11       1          1
11                     12                    16         21       0          0
13                      6                    25         32       0          0
8                      35                     4         10       1          1

In [ ]:
result.head(20)

    Days_since_last_order  Orders_last_6_months  App_Login  Actual  Predicted
18                     38                     5         11       1          1
11                     12                    16         21       0          0
13                      6                    25         32       0          0
8                      35                     4         10       1          1

In [ ]:
print(result)

    Days_since_last_order  Orders_last_6_months  App_Login  Actual  Predicted
18                     38                     5         11       1          1
11                     12                    16         21       0          0
13                      6                    25         32       0          0
8                      35                     4         10       1          1

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, prediction)

print("Accuracy:", accuracy)

Accuracy: 1.0